# Generated by Django 3.2.19 on 2023-06-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_brain_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brain',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
