# Generated by Django 3.2.19 on 2023-06-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_brain_ordint'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginner',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='binary',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='brute',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='dp',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='dpstand',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='dsu',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='graph',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='greed',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='hash',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='implement',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='pair',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='pointer',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='segtree',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='sort',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='sub',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='tree',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
