# Generated by Django 3.2.19 on 2023-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20230701_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='recursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default='1', max_length=20)),
                ('ordint', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
    ]
