# Generated by Django 3.2.19 on 2023-07-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20230701_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginner',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='binary',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='brute',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='dp',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='dpstand',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='dsu',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='graph',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='greed',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='hash',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='implement',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='pair',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='pointer',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='segtree',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='sort',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='sub',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
        migrations.AddField(
            model_name='tree',
            name='ordint',
            field=models.IntegerField(default=models.CharField(default='1', max_length=20)),
        ),
    ]
