# Generated by Django 3.2.19 on 2023-07-04 06:22

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20230704_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginner',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='binary',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='brute',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='dp',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='dpstand',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='dsu',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='graph',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='greed',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='hash',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='implement',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='pair',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='pointer',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='segtree',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='sort',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='sub',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
        migrations.AlterField(
            model_name='tree',
            name='ordint',
            field=models.IntegerField(default=django.db.models.functions.comparison.Cast(models.CharField(default='1', max_length=20), models.IntegerField())),
        ),
    ]
