# Generated by Django 3.2.19 on 2023-07-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20230704_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brain',
            name='ordint',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recursion',
            name='ordint',
            field=models.IntegerField(),
        ),
    ]
