# Generated by Django 3.2.19 on 2023-07-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20230704_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beginner',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='binary',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='brain',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='brute',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='dp',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='dpstand',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='dsu',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='greed',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='hash',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='implement',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='pointer',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='recursion',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='segtree',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='sort',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='ordint',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='ordint',
        ),
    ]
